"""next changes

Revision ID: 1f48bc4e0ed7
Revises: 3ebebf0ed4cf
Create Date: 2026-04-08 16:55:29.302754

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f48bc4e0ed7"
down_revision: Union[str, Sequence[str], None] = "3ebebf0ed4cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
